/// Service API 


export const SERVICE_CATEGORY_GET_REQUEST = "SERVICE_CATEGORY/GET/REQUEST";
export const SERVICE_CATEGORY_GET_SUCCESS = "SERVICE_CATEGORY/GET/SUCCESS";
export const SERVICE_CATEGORY_GET_ERROR = "SERVICE_CATEGORY/GET/ERROR";


export const SERVICE_GET_REQUEST = "SERVICE/GET/REQUEST";
export const SERVICE_GET_SUCCESS = "SERVICE/GET/SUCCESS";
export const SERVICE_GET_ERROR = "SERVICE/GET/ERROR";

/// Product API 
export const SERVICE_PRODUCT_GET_REQUEST = "SERVICE/PRODUCT_GET/REQUEST";
export const SERVICE_PRODUCT_GET_SUCCESS = "SERVICE/PRODUCT_GET/SUCCESS";
export const SERVICE_PRODUCT_GET_ERROR = "SERVICE/PRODUCT_GET/ERROR";