/// RECURRING_ORDER API 

export const RECURRING_ORDER_LIST_REQUEST = "RECURRING_ORDER/LIST/GET";
export const RECURRING_ORDER_LIST_SUCCESS = "RECURRING_ORDER/LIST/SUCCESS";
export const RECURRING_ORDER_LIST_ERROR = "RECURRING_ORDER/LIST/ERROR";


export const RECURRING_ORDER_CANCEL_REQUEST = "RECURRING_ORDER/CANCEL/GET";
export const RECURRING_ORDER_CANCEL_SUCCESS = "RECURRING_ORDER/CANCEL/SUCCESS";
export const RECURRING_ORDER_CANCEL_ERROR = "RECURRING_ORDER/CANCEL/ERROR";
