/// RECURRING_ORDER API 

export const RECURRING_ORDER_LIST_REQUEST = "RECURRING_ORDER/LIST/GET";
export const RECURRING_ORDER_LIST_SUCCESS = "RECURRING_ORDER/LIST/SUCCESS";
export const RECURRING_ORDER_LIST_ERROR = "RECURRING_ORDERLIST/ERROR";
