export const EMAIL_AUTH_SIGNUP_REQUEST = "SIGNUP_02/SIGNUP/REQUEST";
export const EMAIL_AUTH_SIGNUP_SUCCESS = "SIGNUP_02/SIGNUP/SUCCESS";
export const EMAIL_AUTH_SIGNUP_ERROR = "SIGNUP_02/SIGNUP/ERROR";

