# Generated by Django 2.2.20 on 2021-04-12 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='photo',
            field=models.FileField(upload_to='category_photo'),
        ),
        migrations.AlterField(
            model_name='service',
            name='photo',
            field=models.FileField(upload_to='service_photo'),
        ),
    ]
