# Generated by Django 2.2.20 on 2021-04-26 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0002_auto_20210406_1150'),
        ('service', '0002_auto_20210412_0535'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(blank=True, max_length=255, null=True)),
                ('name_es', models.CharField(blank=True, max_length=255, null=True)),
                ('description_en', models.CharField(blank=True, max_length=512, null=True)),
                ('description_es', models.CharField(blank=True, max_length=512, null=True)),
                ('brand_en', models.CharField(blank=True, max_length=255, null=True)),
                ('brand_es', models.CharField(blank=True, max_length=255, null=True)),
                ('photo', models.FileField(upload_to='service_photo')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('weight', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('size', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_recurring', models.BooleanField(default=False)),
                ('sort', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Category')),
                ('petType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet.PetType')),
            ],
        ),
    ]
