# Generated by Django 2.2.20 on 2021-04-26 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
