/// Checkout API 


export const CHECKOUT_CART_ADD_ITEM_REQUEST = "CHECKOUT/CART/ADD_ITEM/REQUEST";
export const CHECKOUT_CART_ADD_ITEM_SUCCESS = "CHECKOUT/CART/ADD_ITEM/SUCCESS";
export const CHECKOUT_CART_ADD_ITEM_ERROR = "CHECKOUT/CART/ADD_ITEM/ERROR";

export const CHECKOUT_ORDER_ADD_REQUEST = "CHECKOUT/ORDER/ADD/REQUEST";
export const CHECKOUT_ORDER_ADD_SUCCESS = "CHECKOUT/ORDER/ADD/SUCCESS";
export const CHECKOUT_ORDER_ADD_ERROR = "CHECKOUT/ORDER/ADD/ERROR";

export const CHECKOUT_CART_UPDATE_ITEM_REQUEST = "CHECKOUT/CART/UPDATE_ITEM/REQUEST";
export const CHECKOUT_CART_UPDATE_ITEM_SUCCESS = "CHECKOUT/CART/UPDATE_ITEM/SUCCESS";
