# Generated by Django 2.2.20 on 2021-04-29 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_product_stripe_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PN', 'Pending'), ('PD', 'Paid')], default='PN', max_length=2),
        ),
    ]
