# Generated by Django 2.2.20 on 2021-05-06 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='order_every',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
