# Generated by Django 2.2.20 on 2021-06-01 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_product_order_every'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_recurr_cancel',
            field=models.BooleanField(default=False),
        ),
    ]
