# Generated by Django 2.2.20 on 2021-04-12 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_stripe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='dynamic_last4',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='card',
            name='exp_month',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='card',
            name='exp_year',
            field=models.IntegerField(default=0),
        ),
    ]
