# Generated by Django 2.2.20 on 2021-04-12 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_stripe', '0002_auto_20210412_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='funding',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
