# Generated by Django 2.2.20 on 2021-04-12 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_stripe', '0003_auto_20210412_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='dynamic_last4',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
