# Generated by Django 2.2.20 on 2021-04-30 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_auto_20210430_0517'),
        ('payment_stripe', '0006_productprices'),
    ]

    operations = [
        migrations.AddField(
            model_name='productprices',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.Service'),
        ),
        migrations.AlterField(
            model_name='productprices',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.Product'),
        ),
    ]
