# Generated by Django 2.2.20 on 2021-04-30 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_stripe', '0007_auto_20210430_0554'),
    ]

    operations = [
        migrations.AddField(
            model_name='productprices',
            name='recurring_interval',
            field=models.CharField(blank=True, default='month', max_length=255, null=True),
        ),
    ]
