# Generated by Django 2.2.20 on 2021-05-08 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_stripe', '0011_auto_20210508_0448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='requestBody',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
