# Generated by Django 2.2.20 on 2021-05-08 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_stripe', '0012_auto_20210508_0508'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionpayments',
            name='paymentType',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
