# Generated by Django 2.2.20 on 2021-05-21 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_stripe', '0015_subscriptionpayments_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptionpayments',
            old_name='date',
            new_name='stripe_date',
        ),
    ]
