# Generated by Django 2.2.20 on 2021-05-26 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_stripe', '0016_auto_20210521_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productprices',
            name='recurring_interval',
            field=models.CharField(blank=True, default='month', max_length=255, null=True),
        ),
    ]
