# Generated by Django 2.2.20 on 2021-06-01 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_stripe', '0017_auto_20210526_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
