# Generated by Django 2.2.20 on 2021-04-12 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment_stripe', '0002_auto_20210412_1203'),
        ('users', '0003_user_stripe_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='default_card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payment_stripe.Card'),
        ),
    ]
