/// Pet API 


export const USER_PET_GET_REQUEST = "USER_PET/GET/REQUEST";
export const USER_PET_GET_SUCCESS = "USER_PET/GET/SUCCESS";
export const USER_PET_GET_ERROR = "USER_PET/GET/ERROR";

export const USER_PET_ADD_REQUEST = "USER_PET/ADD/REQUEST";
export const USER_PET_ADD_SUCCESS = "USER_PET/ADD/SUCCESS";
export const USER_PET_ADD_ERROR = "USER_PET/ADD/ERROR";

export const USER_PET_UPDATE_REQUEST = "USER_PET/UPDATE/REQUEST";
export const USER_PET_UPDATE_SUCCESS = "USER_PET/UPDATE/SUCCESS";
export const USER_PET_UPDATE_ERROR = "USER_PET/UPDATE/ERROR";

export const USER_PET_DELETE_REQUEST = "USER_PET/DELETE/REQUEST";
export const USER_PET_DELETE_SUCCESS = "USER_PET/DELETE/SUCCESS";
export const USER_PET_DELETE_ERROR = "USER_PET/DELETE/ERROR";

export const USER_PET_SELECT_REQUEST = "USER_PET/SELECT/REQUEST";
export const USER_PET_SELECT_SUCCESS = "USER_PET/SELECT/SUCCESS";
export const USER_PET_SELECT_ERROR = "USER_PET/SELECT/ERROR";

export const USER_PET_TYPE_GET_REQUEST = "USER_PET/TYPE/GET/REQUEST";
export const USER_PET_TYPE_GET_SUCCESS = "USER_PET/TYPE/GET/SUCCESS";
export const USER_PET_TYPE_GET_ERROR = "USER_PET/TYPE/GET/ERROR";

export const USER_PET_BREED_GET_REQUEST = "USER_PET/BREED/GET/REQUEST";
export const USER_PET_BREED_GET_SUCCESS = "USER_PET/BREED/GET/SUCCESS";
export const USER_PET_BREED_GET_ERROR = "USER_PET/BREED/GET/ERROR";

export const USER_PET_BREED_SET_SUCCESS = "USER_PET/BREED/SET/SUCCESS";


export const USER_PROFILE_UPDATE_REQUEST = "USER_PROFILE/UPDATE/REQUEST";
export const USER_PROFILE_UPDATE_SUCCESS = "USER_PROFILE/UPDATE/GET/SUCCESS";
export const USER_PROFILE_UPDATE_ERROR = "USER_PROFILE/UPDATE/GET/ERROR";

export const USER_CARD_GET_REQUEST = "USER_CARD/GET/REQUEST";
export const USER_CARD_GET_SUCCESS = "USER_CARD/GET/SUCCESS";
export const USER_CARD_GET_ERROR = "USER_CARD/GET/ERROR";

export const USER_CARD_CREATE_REQUEST = "USER_CARD/CREATE/REQUEST";
export const USER_CARD_CREATE_SUCCESS = "USER_CARD/CREATE/SUCCESS";
export const USER_CARD_CREATE_ERROR = "USER_CARD/CREATE/ERROR";


export const USER_CARD_UPDATE_REQUEST = "USER_CARD/UPDATE/REQUEST";
export const USER_CARD_UPDATE_SUCCESS = "USER_CARD/UPDATE/SUCCESS";
export const USER_CARD_UPDATE_ERROR = "USER_CARD/UPDATE/ERROR";

export const USER_CARD_DELETE_REQUEST = "USER_CARD/DELETE/REQUEST";
export const USER_CARD_DELETE_SUCCESS = "USER_CARD/DELETE/SUCCESS";
export const USER_CARD_DELETE_ERROR = "USER_CARD/DELETE/ERROR";


export const USER_SHOW_PET_SELECTOR_SUCCESS = "USER/SHOW_PET_SELECTOR/SUCCESS";
export const USER_HIDE_PET_SELECTOR_SUCCESS = "USER/HIDE_PET_SELECTOR/SUCCESS";


