export const EMAIL_AUTH_SIGNUP_REQUEST = "SIGNUP_02/SIGNUP/REQUEST";
export const EMAIL_AUTH_SIGNUP_SUCCESS = "SIGNUP_02/SIGNUP/SUCCESS";
export const EMAIL_AUTH_SIGNUP_ERROR = "SIGNUP_02/SIGNUP/ERROR";

export const EMAIL_AUTH_LOGIN_REQUEST = "EMAIL_AUTH_4/LOGIN/REQUEST";
export const EMAIL_AUTH_LOGIN_SUCCESS = "EMAIL_AUTH_4/LOGIN/SUCCESS";
export const EMAIL_AUTH_LOGIN_ERROR = "EMAIL_AUTH_4/LOGIN/ERROR";


export const EMAIL_AUTH_LOGOUT = "EMAIL_AUTH_4/LOGOUT";

export const EMAIL_AUTH_PASSWORD_RECOVER_REQUEST =
  "EMAIL_AUTH_4/PASSORD_RECOVER/REQUEST";
export const EMAIL_AUTH_PASSWORD_RECOVER_SUCCESS =
  "EMAIL_AUTH_4/PASSORD_RECOVER/SUCCESS";
export const EMAIL_AUTH_PASSWORD_RECOVER_ERROR =
  "EMAIL_AUTH_4/PASSORD_RECOVER/ERROR";