/// Pet API 


export const USER_PET_GET_REQUEST = "USER_PET/GET/REQUEST";
export const USER_PET_GET_SUCCESS = "USER_PET/GET/SUCCESS";
export const USER_PET_GET_ERROR = "USER_PET/GET/ERROR";

export const USER_PET_ADD_REQUEST = "USER_PET/ADD/REQUEST";
export const USER_PET_ADD_SUCCESS = "USER_PET/ADD/SUCCESS";
export const USER_PET_ADD_ERROR = "USER_PET/ADD/ERROR";

export const USER_PET_UPDATE_REQUEST = "USER_PET/UPDATE/REQUEST";
export const USER_PET_UPDATE_SUCCESS = "USER_PET/UPDATE/SUCCESS";
export const USER_PET_UPDATE_ERROR = "USER_PET/UPDATE/ERROR";

export const USER_PET_DELETE_REQUEST = "USER_PET/DELETE/REQUEST";
export const USER_PET_DELETE_SUCCESS = "USER_PET/DELETE/SUCCESS";
export const USER_PET_DELETE_ERROR = "USER_PET/DELETE/ERROR";

export const USER_PET_SELECT_REQUEST = "USER_PET/SELECT/REQUEST";
export const USER_PET_SELECT_SUCCESS = "USER_PET/SELECT/SUCCESS";
export const USER_PET_SELECT_ERROR = "USER_PET/SELECT/ERROR";

export const USER_PET_TYPE_GET_REQUEST = "USER_PET/TYPE/GET/REQUEST";
export const USER_PET_TYPE_GET_SUCCESS = "USER_PET/TYPE/GET/SUCCESS";
export const USER_PET_TYPE_GET_ERROR = "USER_PET/TYPE/GET/ERROR";

export const USER_PET_BREED_GET_REQUEST = "USER_PET/BREED/GET/REQUEST";
export const USER_PET_BREED_GET_SUCCESS = "USER_PET/BREED/GET/SUCCESS";
export const USER_PET_BREED_GET_ERROR = "USER_PET/BREED/GET/ERROR";